
Project
Core3
.git
MMOCoreORB
.externalToolBuilders
.settings
bin
conf
custom_scripts
databases
log
navmeshes
scripts
ai
commands
custom_scripts
loot
managers
mobile
object
battlefield_marker
building
cell
construction_contract
counting
creature
draft_schematic
factory
group
guild
installation
intangible
jedi_manager
manufacture_schematic
mission
mobile
object
path_waypoint
player
resource_container
ship
soundobject
static
tangible
token
universe
waypoint
weapon
active_area.lua
allobjects.lua
badge_area.lua
camp_area.lua
clientmain.lua
fs_village_area.lua
main.lua
mission_recon_area.lua
mission_spawn_area.lua
object.lua
objects.lua
region_area.lua
region_navmesh.lua
sarlacc_area.lua
serverobjects.lua
SharedBattlefieldMarkerObjectTemplate.lua
SharedBuildingObjectTemplate.lua
SharedCellObjectTemplate.lua
SharedConstructionContractObjectTemplate.lua
SharedCountingObjectTemplate.lua
SharedCreatureObjectTemplate.lua
SharedDraftSchematicObjectTemplate.lua
SharedFactoryObjectTemplate.lua
SharedGroupObjectTemplate.lua
SharedGuildObjectTemplate.lua
SharedInstallationObjectTemplate.lua
SharedIntangibleObjectTemplate.lua
SharedJediManagerTemplate.lua
SharedManufactureSchematicObjectTemplate.lua
SharedMissionDataObjectTemplate.lua
SharedMissionListEntryObjectTemplate.lua
SharedMissionObjectTemplate.lua
SharedObjectTemplate.lua
SharedPlayerObjectTemplate.lua
SharedResourceContainerObjectTemplate.lua
SharedShipObjectTemplate.lua
SharedStaticObjectTemplate.lua
SharedTangibleObjectTemplate.lua
SharedTokenObjectTemplate.lua
SharedUniverseObjectTemplate.lua
SharedWaypointObjectTemplate.lua
SharedWeaponObjectTemplate.lua
spawn_area.lua
screenplays
battlefields
caves
cities
crackdown
dungeon
events
gcw
jedi
junk_dealer
poi
quest_tasks
racetracks
record_keepers
space
static_spawns
sui
tasks
tests
themepark
tools
trainers
treasure_map
tutorial
utils
village
checklnum.lua
conv_handler.lua
example_screenplay.lua
helperfuncs.lua
playerTriggers.lua
screenplay.lua
screenplays.lua
skills
staff
utils
testscript.lua
terrain
.gitignore
ccore3
core3
core3-default.supp
core3client
dcore3
hcore3
testsuite3
vcore3
vcore3client
build
cmake
doc
docker
helm
sql
src
autogen
client
conf
CMakeLists.txt
CommandManager.h
ConfigManager.cpp
ConfigManager.h
odb
pathfinding
server
chat
db
features
login
metrics
ping
status
utils
web
zone
managers
auction
city
collision
combat
components
conversation
crafting
creature
credit
director
faction
frs
gcw
observers
ImperialChatObserver.cpp
ImperialChatObserver.idl
ProbotObserver.idl
ProbotObserverImplementation.cpp
SquadObserver.idl
SquadObserverImplementation.cpp
sessions
tasks
GCWBaseShutdownObserver.idl
GCWBaseShutdownObserverImplementation.cpp
GCWManager.idl
GCWManagerImplementation.cpp
SecurityPatrolSpawn.h
TerminalSpawn.h
group
guild
holocron
jedi
loot
minigames
mission
name
object
objectcontroller
planet
player
radial
reaction
resource
ship
skill
space
statistics
stringid
structure
sui
vendor
visibility
weather
ZoneManager.idl
objects
area
auction
building
cell
creature
ai
bt
events
variables
AiAgent.idl
AiAgentImplementation.cpp
Creature.idl
CreatureImplementation.cpp
CreatureTemplate.cpp
CreatureTemplate.h
DroidObject.idl
DroidObjectImplementation.cpp
HelperDroidObject.idl
HelperDroidObjectImplementation.cpp
LuaAiAgent.cpp
LuaAiAgent.h
NonPlayerCreatureObject.idl
NonPlayerCreatureObjectImplementation.cpp
PatrolPoint.h
PatrolPointsVector.h
buffs
commands
components
conversation
credits
damageovertime
events
AnimationTask.h
BurstRunNotifyAvailableEvent.h
CamoTask.h
DespawnCreatureOnPlayerDissappear.h
DespawnCreatureTask.h
DespawnDynamicSpawnTask.h
DizzyFallDownEvent.h
DroidAutoRepairTask.h
DroidDetonationTask.h
DroidEffectsTask.h
DroidHarvestTask.h
DroidMerchantBarkerTask.h
DroidPlaybackEvent.h
DroidPlaybackTask.h
DroidPowerTask.h
DroidSkillModTask.h
DroidStimpackTask.h
DroidTrapTask.h
ForceIntimidateTask.h
GallopNotifyAvailableEvent.h
InjuryTreatmentTask.h
InvisibleDelayEvent.h
JediMindTrickRemovalTask.h
MilkCreatureTask.h
PetIncapacitationRecoverTask.h
ProposeUnityExpiredTask.h
RespawnCreatureTask.h
SampleDeedTask.h
SampleDnaTask.h
SpawnCreatureTask.h
SpiceDownerAnimationTask.h
TameCreatureTask.h
ThrowTrapTask.h
VehicleDecayTask.h
sui
variables
BuffAttribute.h
CommandQueue.cpp
CommandQueue.h
CreatureObject.idl
CreatureObjectImplementation.cpp
LuaCreatureObject.cpp
LuaCreatureObject.h
SpeedMultiplierModChanges.h
VehicleObject.idl
VehicleObjectImplementation.cpp
draftschematic
factorycrate
group
guild
installation
intangible
manufactureschematic
mission
pathfinding
player
region
components
events
CitizenList.h
CityRegion.idl
CityRegionImplementation.cpp
CityStructureInventory.h
LuaCityRegion.cpp
LuaCityRegion.h
Region.idl
RegionCenterPoint.h
RegionCenterPointList.h
RegionImplementation.cpp
SpawnArea.idl
SpawnAreaImplementation.cpp
SpawnAreaObserver.idl
resource
scene
ship
staticobject
structure
tangible
attachment
component
components
consumable
deed
eventperk
firework
fishing
loot
misc
pharmaceutical
powerup
sign
tasks
terminal
threat
ticket
tool
variables
weapon
wearables
Container.idl
ContainerImplementation.cpp
DespawnLairOnPlayerDisappear.cpp
DespawnLairOnPlayerDisappear.h
Instrument.idl
InstrumentImplementation.cpp
LairObject.idl
LuaTangibleObject.cpp
LuaTangibleObject.h
RelockLootContainerEvent.h
TangibleObject.idl
TangibleObjectImplementation.cpp
transaction
waypoint
packets
ActiveAreaQuadTree.cpp
ActiveAreaQuadTree.h
ActiveAreasVector.h
CloseObjectsVector.cpp
CloseObjectsVector.h
InRangeObjectsVector.h
MessageCallbackFactory.h
QuadTree.cpp
QuadTree.h
QuadTreeEntry.idl
QuadTreeEntryImplementation.cpp
QuadTreeNode.h
QuadTreeReference.cpp
QuadTreeReference.h
ShutdownTask.h
Zone.idl
ZoneClientSession.idl
ZoneClientSessionImplementation.cpp
ZoneContainerComponent.cpp
ZoneContainerComponent.h
ZoneHandler.h
ZoneImplementation.cpp
ZoneLoadManagersTask.h
ZonePacketHandler.cpp
ZonePacketHandler.h
ZoneProcessServer.idl
ZoneProcessServerImplementation.cpp
ZoneReference.cpp
ZoneReference.h
ZoneServer.idl
ZoneServerImplementation.cpp
ServerCore.cpp
ServerCore.h
templates
terrain
tests
BasicScreenPlayTest.cpp
BasicTerrainTest.cpp
CircularAreaShapeTest.cpp
CMakeLists.txt
CommandLuaTest.cpp
ConfigManagerTest.cpp
CreatureObjectTest.cpp
CreditObjectTest.cpp
DeadlockTestBase.cpp
DeadlockTestBase.h
JediManagerTest.cpp
LuaMobileTest.cpp
MockBehavior.h
MockCompositeBehavior.h
RectangularAreaShapeTest.cpp
RingAreaShapeTest.cpp
TerrainManagerTest.cpp
TestCore.h
ZoneTest.cpp
tre3
.gitignore
CMakeLists.txt
CoreProcess.h
main.cpp
utils
.cdtproject
.clang_complete
.clang-format
.cproject
.gitignore
.project
AUTHORS
ChangeLog
CMakeLists.txt
codetemplates.xml
COPYING
Makefile
NEWS
README
README.osx
suppressions.txt
.gitignore
.gitmodules
COPYING
README.md
config.lua
droid_storage_compartment.lua
InstallationObjectImplementation.cpp
harvest_module.lua
ConfigManager.h
CreatureManager.idl
CreatureManagerImplementation.cpp
DynamicSpawnObserverImplementation.cpp
SpawnObserverImplementation.cpp
CreatureObjectImplementation.cpp
AiAgent.idl
AiAgentImplementation.cpp
SquadObserverImplementation.cpp
SquadObserver.idl
CreatureImplementation.cpp
DroidObjectImplementation.cpp
PlayerManagerCommand.h
RespawnCreatureTask.h
SpawnAreaImplementation.cpp
DespawnLairOnPlayerDisappear.cpp
49
50
51
52
53
54
55
56
57
58
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
  @local
  public native AiAgent getMember(int teamMemberIndex);
 
  @local
  public native void despawnSquad();
 
  @local
  public native boolean despawnMembersCloseToLambdaShuttle(@dereferenced final Vector3 landingPosition, boolean forcedCleanup);
}
 
import engine.util.Observable;
import system.thread.Mutex;
 
include engine.log.Logger;
include system.util.Vector;
include engine.util.u3d.Vector3;
 
class SquadObserver extends Observer implements Logger {
  @local
  @dereferenced
  protected Vector<AiAgent> teamMembers;
 
  @dereferenced
  protected transient Mutex squadLock;
 
  public SquadObserver() {
    super();
 
    Logger.setLoggingName("SquadObserver");
  }
 
  @local
  @read
  public int size() {
    return teamMembers.size();
  }
 
  @local
  @preLocked
  public native void removeMember(int index) {
    teamMembers.remove(index);
  }
 
  @local
  public native void addMember(AiAgent member);
 
￼
No results found for '// Check'Finding with Options: Case Insensitive￼
￼
￼
￼
// Check
￼
 
no results
￼Find
￼Find All
 
Replace in current buffer￼
￼Replace
￼Replace All
